# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_BFM": "fmm.ipynb",
         "load_BFM_info": "fmm.ipynb",
         "load_uv_coords": "fmm.ipynb",
         "load_pncc_code": "fmm.ipynb",
         "get_organ_ind": "fmm.ipynb",
         "estimate_shape": "fmm.ipynb",
         "estimate_expression": "fmm.ipynb",
         "fit_points": "fmm.ipynb",
         "fit_points_for_show": "fmm.ipynb",
         "MorphabelModel": "fmm.ipynb",
         "load_vf": "io.ipynb",
         "write_vf": "io.ipynb",
         "deg2rad": "transform.ipynb",
         "axis_angle_rotation": "transform.ipynb",
         "angle2matrix": "transform.ipynb",
         "similarity_transform": "transform.ipynb",
         "transform": "transform.ipynb",
         "rotate": "transform.ipynb",
         "matrix2angle": "transform.ipynb",
         "denormal_mesh": "transform.ipynb",
         "test": "utils.ipynb",
         "test_eq": "utils.ipynb",
         "simplify_qd": "utils.ipynb"}

modules = ["fmm.py",
           "io.py",
           "transform.py",
           "utils.py"]

doc_url = "https://invisprints.github.io/face_3dmm/"

git_url = "https://github.com/invisprints/face_3dmm/tree/master/"

def custom_doc_links(name): return None
