# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "io.ipynb"}

modules = ["io.py"]

doc_url = "https://invisprints.github.io/face_3dmm/"

git_url = "https://github.com/invisprints/face_3dmm/tree/master/"

def custom_doc_links(name): return None
