# AUTOGENERATED! DO NOT EDIT! File to edit: io.ipynb (unless otherwise specified).

__all__ = ['load_vf', 'write_vf']

# Cell
import open3d as o3d
import numpy as np
from .utils import test_eq

# Cell
def load_vf(fp: str):
    mesh = o3d.io.read_triangle_mesh(fp)
    return np.asarray(mesh.vertices), np.asarray(mesh.triangles)

def write_vf(fp: str, verts, faces=None, flip_face=False):
    faces = faces if not flip_face else faces[:, ::-1]
    mesh = o3d.geometry.TriangleMesh()
    mesh.triangles = o3d.utility.Vector3iVector(faces)
    mesh.vertices = o3d.utility.Vector3dVector(verts)
    o3d.io.write_triangle_mesh(fp, mesh)